repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Backend hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        name: ruff (python)
        types: [python]
        args: ["--fix", "--fix-only", "--extend-ignore=E501,E203"]
        files: ^src/

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        types: [python]
        args: ["--profile", "black", "--src", "src"]
        files: ^src/

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8 (python)
        types: [python]
        args: ["--extend-ignore=E501,E203"]
        files: ^src/

  # Tests
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        args: ["-v", "--tb=short"]
