repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Backend hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        name: ruff (python)
        types: [file, python]
        files: ^src/.*\.py$
        args: ["--fix", "--fix-only", "--extend-ignore=E501,E203"]

      - id: ruff-format
        name: ruff-format (cython, pyi)
        files: ^src/.*\.(pyx|pyi)$
        args: ["--fix", "--fix-only", "--extend-ignore=E501,E203"]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        files: ^src/.*\.py$
        args: [-o, alembic, --src, "{{cookiecutter.project_slug}}/backend"]

      - id: isort
        name: isort (cython)
        files: ^src/.*\.pyx$

      - id: isort
        name: isort (pyi)
        files: ^src/.*\.pyi$

  # Frontend hooks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.0"
    hooks:
      - id: prettier
        files: ^src/static/js/.*\.(js|jsx|ts|tsx)$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v7.20.0"
    hooks:
      - id: eslint
        files: ^src/static/js/.*\.(js|jsx|ts|tsx)$
