"""Initial tables

Revision ID: 0a0a7ed754b8
Revises: 1098ffdf950b
Create Date: 2025-07-12 17:24:03.133756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0a7ed754b8'
down_revision: Union[str, Sequence[str], None] = '1098ffdf950b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('is_staff', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    op.drop_column('user', 'hash_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'is_staff')
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
