"""init

Revision ID: 0275e89e75f8
Revises: 38daa5c6e729
Create Date: 2025-07-21 10:19:43.667514

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0275e89e75f8"
down_revision: str | Sequence[str] | None = "38daa5c6e729"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
