"""Updated User

Revision ID: 38daa5c6e729
Revises: 9bdfc86d4116
Create Date: 2025-07-21 10:17:21.787471

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "38daa5c6e729"
down_revision: str | Sequence[str] | None = "9bdfc86d4116"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
