"""Updated User

Revision ID: 4177fe2d2039
Revises: 082e2be7c949
Create Date: 2025-07-21 10:15:39.105514

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4177fe2d2039"
down_revision: str | Sequence[str] | None = "082e2be7c949"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
