"""init

Revision ID: 6e57a7ccf0cb
Revises: 0275e89e75f8
Create Date: 2025-07-21 10:21:14.576521

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6e57a7ccf0cb"
down_revision: Union[str, Sequence[str], None] = "0275e89e75f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
