"""init

Revision ID: 6e57a7ccf0cb
Revises: 0275e89e75f8
Create Date: 2025-07-21 10:21:14.576521

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6e57a7ccf0cb"
down_revision: str | Sequence[str] | None = "0275e89e75f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
