"""Fixed meeting model

Revision ID: b3a0d700e300
Revises: 92d8426fdb69
Create Date: 2025-07-21 16:13:54.731968

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3a0d700e300"
down_revision: Union[str, Sequence[str], None] = "92d8426fdb69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meetings", "jira_ticket_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meetings",
        sa.Column(
            "jira_ticket_id", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
