name: Pre-commit and Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Cache pre-commit hooks
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run pre-commit hooks
      run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
    - uses: actions/checkout@v4

    - name: Run tests in Docker container
      run: |
        docker run --rm \
          -v $(pwd):/app \
          -w /app \
          python:3.12-slim \
          sh -c "
            apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/* &&
            pip install -e '.[dev]' && 
            python -m pytest src/tests/ -v --tb=short
          "

  build:
    runs-on: ubuntu-latest
    needs: [pre-commit, test]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker meta
      id: meta
      run: |
        if [ "${{ github.ref }}" = "refs/heads/master" ]; then
          echo "tags=meet2jira:latest,meet2jira:${{ github.sha }}" >> $GITHUB_OUTPUT
        else
          echo "tags=meet2jira:pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
        fi

    - name: Build production Docker image
      run: |
        TAG=$(echo "${{ steps.meta.outputs.tags }}" | cut -d',' -f1)
        docker build . --file Dockerfile --tag $TAG
        echo "Built production image: $TAG"